# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pixart_localization/world_point.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class world_point(genpy.Message):
  _md5sum = "4c1801fffad721cf6519e3411a1948c7"
  _type = "pixart_localization/world_point"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/PointStamped pt
uint16 camera_id
uint8 point_id

================================================================================
MSG: geometry_msgs/PointStamped
# This represents a Point with reference coordinate frame and timestamp
Header header
Point point

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['pt','camera_id','point_id']
  _slot_types = ['geometry_msgs/PointStamped','uint16','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pt,camera_id,point_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(world_point, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pt is None:
        self.pt = geometry_msgs.msg.PointStamped()
      if self.camera_id is None:
        self.camera_id = 0
      if self.point_id is None:
        self.point_id = 0
    else:
      self.pt = geometry_msgs.msg.PointStamped()
      self.camera_id = 0
      self.point_id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.pt.header.seq, _x.pt.header.stamp.secs, _x.pt.header.stamp.nsecs))
      _x = self.pt.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3dHB().pack(_x.pt.point.x, _x.pt.point.y, _x.pt.point.z, _x.camera_id, _x.point_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pt is None:
        self.pt = geometry_msgs.msg.PointStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pt.header.seq, _x.pt.header.stamp.secs, _x.pt.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pt.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.pt.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 27
      (_x.pt.point.x, _x.pt.point.y, _x.pt.point.z, _x.camera_id, _x.point_id,) = _get_struct_3dHB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.pt.header.seq, _x.pt.header.stamp.secs, _x.pt.header.stamp.nsecs))
      _x = self.pt.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3dHB().pack(_x.pt.point.x, _x.pt.point.y, _x.pt.point.z, _x.camera_id, _x.point_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pt is None:
        self.pt = geometry_msgs.msg.PointStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pt.header.seq, _x.pt.header.stamp.secs, _x.pt.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pt.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.pt.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 27
      (_x.pt.point.x, _x.pt.point.y, _x.pt.point.z, _x.camera_id, _x.point_id,) = _get_struct_3dHB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3dHB = None
def _get_struct_3dHB():
    global _struct_3dHB
    if _struct_3dHB is None:
        _struct_3dHB = struct.Struct("<3dHB")
    return _struct_3dHB
