# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from toycode/cam.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class cam(genpy.Message):
  _md5sum = "b6e378fbcfee096e6fdfd7d90c3f26de"
  _type = "toycode/cam"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint16 x
uint16 y
uint16 camera_id
uint8 point_id
time stamp
"""
  __slots__ = ['x','y','camera_id','point_id','stamp']
  _slot_types = ['uint16','uint16','uint16','uint8','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,camera_id,point_id,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(cam, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0
      if self.y is None:
        self.y = 0
      if self.camera_id is None:
        self.camera_id = 0
      if self.point_id is None:
        self.point_id = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.x = 0
      self.y = 0
      self.camera_id = 0
      self.point_id = 0
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3HB2I().pack(_x.x, _x.y, _x.camera_id, _x.point_id, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 15
      (_x.x, _x.y, _x.camera_id, _x.point_id, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_3HB2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3HB2I().pack(_x.x, _x.y, _x.camera_id, _x.point_id, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 15
      (_x.x, _x.y, _x.camera_id, _x.point_id, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_3HB2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3HB2I = None
def _get_struct_3HB2I():
    global _struct_3HB2I
    if _struct_3HB2I is None:
        _struct_3HB2I = struct.Struct("<3HB2I")
    return _struct_3HB2I
